### ISSUE TITLE
Incompatibility with file-icons plugin

### ISSUE THREAD

**Issue by pdonias** [paulpflug/foldername-tabs#15]
Hi!

I'm using [file-icons](https://github.com/file-icons/atom) plugin along with foldername-tabs and I have an issue when a file name is too long.

With **file-icons** only:
![capture du 2017-01-12 10-03-38](https://cloud.githubusercontent.com/assets/10992860/21883243/71b33dc4-d8ae-11e6-99ae-b346a83ac667.png)

With **foldername-tabs** only:
![capture du 2017-01-12 10-05-46](https://cloud.githubusercontent.com/assets/10992860/21883300/b85bf7b6-d8ae-11e6-9444-b1187a88d571.png)

With **both** plugins:
![capture du 2017-01-12 10-03-25](https://cloud.githubusercontent.com/assets/10992860/21883308/c0ac07d0-d8ae-11e6-8bf1-f70e891cc908.png)

As you can see, when I use both plugins at the same time, the tab name disappears as if both the icon and the text couldn't fit inside the tab.

I'm aware there can be a lot of incompatibilities like this one with all the plugins available on Atom and you can't handle all of them but if there was a way to fix this one, it would be great :)

**Comment by rcrichton** [comment]
I'm also seeing this bug, it looks like the title is being pushed to the next line below the icon but is not visible.

**Comment by rcrichton** [comment]
I can't find a good css solution to rectify this, but here is a workaround that works:

Add the following to your Atom stylesheet (Edit > Stylesheet...):
```css
/* fix foldername-tabs package incompatibility - https://github.com/paulpflug/foldername-tabs/issues/15 */
.foldername-tabs {
  width: 0%;
}
```

**Comment by gregorygenova** [comment]
I fix it like that :

```css
.foldername-tabs {
  width: 1rem;
}
```

**Comment by jiafra** [comment]
I yolo'ed:
```css
.tab-bar .tab .title {
    display: flex;
    align-items: center;
}

div.foldername-tabs {
    top: 0; /* Adjust for theme */
    width: 100%;
    text-align:left; /* Optional */
}

div.foldername-tabs > span.folder {
    opacity: 0.6;
}
```

with pleasing results in One Dark theme:

![tabtweak](https://cloud.githubusercontent.com/assets/4294007/24631994/898f3cdc-1890-11e7-83da-d78dd0664dea.jpg)
